spring:
  datasource:
    url: jdbc:mysql://localhost:3307/content_center
    hikari:
      username: root
      password: 123
      driver-class-name: com.mysql.cj.jdbc.Driver

  cloud:
    nacos:
      discovery:
        # 指定 nacos server 的地址
        server-addr: localhost:8848
  application:
    name: content-center
server:
  port: 8010
